import type { Metadata } from "next";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";
import Footer from "@/components/ui/Footer";
import Navbar from "@/components/ui/Header";
import { UserProvider } from "@/contexts/UserContext";

export const metadata: Metadata = {
  title: "Hello | Nền tảng luyện viết IELTS với AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="vi">
      <body className="bg-gray-50">
        <UserProvider>
          <Navbar />
          <main className="min-h-screen">{children}</main>
          <Footer />
        </UserProvider>
      </body>
    </html>
  );
}
